version: "3"
services:
  node-app:
    build: .
    ports:
      - "${PORT}:${PORT}"    
    # stdin_open: true 
    # tty: true  
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
    - ./.env