version: "3"
services:
  # nginx:
  #   image: nginx:stable-alpine
  #   ports:
  #     - "3000-3001:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  
  server:
    build: .
    image: node:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - omics

  server2:
    build: .
    image: node:latest
    ports: 
      - "3001:3001"
    environment:
      - PORT=3001

  omics:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null 
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=IBG4
      - MONGO_INITDB_ROOT_PASSWORD=31415
    volumes:
      - omics-db:/data/db
    
volumes:
  omics-db: