version: "3"
services:
  # nginx:
  #   ports:
  #     - "3000:80"  
  server:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=IBG4
      - MONGO_PASSWORD=31415
    command: npm run dev
 
  server2:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev2
 
  omics:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=IBG4
      - MONGO_INITDB_ROOT_PASSWORD=31415

